### ISSUE TITLE
Unable to build the monster example with current spirit

### ISSUE THREAD

**Issue by ldionne** [wichtounet/spirit_x3_tests#1]
I'm investigating the relation between long symbol names and slow compile-times, and @K-ballo pointed this repository to me. I'm trying to build the `monster` example using the Spirit included in Boost 1.60, but I'm getting errors of things missing from the `boost::spirit::x3` namespace.

I'm just wondering whether I might be doing something obviously wrong, or if it's just because X3 evolved in a non-backwards compatible manner and this test wasn't updated. If that's the latter, I don't expect you to do anything about it.

**Comment by wichtounet** [comment]
Hi, 

There are indeed errors, even on 1.59. I have fixed the obvious one, but I don't intend to fix everything. If you find the source of the last errors, I'd be glad to include them. 

If you just wanna investigate, you can try my eddic repository, I have an even bigger grammar. You can use: 

make release/src/parser_x3/SpiritParser.cpp.o

to compile only the X3 grammar. It works on Boost 1.59.

**Comment by ldionne** [comment]
Thanks! I'll take a look at eddic.

**Comment by wichtounet** [comment]
Don't hesitate to open another issue in eddic if you notice somewhere not working ;)

**Comment by ldionne** [comment]
Alright, thanks!
